services:
  basicvids_redis:
    image: redis:7-alpine
    container_name: basicvids_redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - basicvids
    restart: unless-stopped
    mem_limit: 256m

networks:
  basicvids:
    external: true
    name: basicvids

volumes:
  redis_data:
